import {
  ArchiveRestore,
  Bell,
  BellRing,
  Bot,
  Boxes,
  Building2,
  ClipboardCheck,
  ClipboardList,
  Compass,
  FileSearch,
  Handshake,
  KeyRound,
  LogIn,
  PackageCheck,
  RadioTower,
  RotateCcw,
  SearchX,
  ShieldCheck,
  Truck,
  UserPlus,
  Users,
  Warehouse,
} from 'lucide-react'

export const appIcons = {
  access: ClipboardCheck,
  alerts: Bell,
  alertsActive: BellRing,
  assistant: Bot,
  audit: FileSearch,
  governance: ShieldCheck,
  inventory: Boxes,
  login: LogIn,
  notFound: SearchX,
  onboarding: UserPlus,
  operations: Compass,
  orders: ClipboardList,
  outbox: RadioTower,
  password: KeyRound,
  recovery: RotateCcw,
  relationships: Handshake,
  service: Handshake,
  shipments: Truck,
  tenants: Building2,
  users: Users,
  warehouse: Warehouse,
  warehouseWork: PackageCheck,
  receiving: ArchiveRestore,
} as const

export type AppIconName = keyof typeof appIcons
