DELETE FROM notification_preferences
WHERE channel NOT IN ('IN_APP')
   OR topic NOT IN ('ACCOUNT_LIFECYCLE', 'OPERATIONS', 'SERVICE_ACCOUNTABILITY', 'OUTBOX_HEALTH');

DELETE FROM notification_deliveries
WHERE channel NOT IN ('IN_APP')
   OR topic NOT IN ('ACCOUNT_LIFECYCLE', 'OPERATIONS', 'SERVICE_ACCOUNTABILITY', 'OUTBOX_HEALTH')
   OR status NOT IN ('RECORDED', 'READ', 'PROVIDER_RECORDED', 'SKIPPED_BY_PREFERENCE')
   OR delivery_stage NOT IN ('PREPARED', 'LOCAL_RECORDED', 'SKIPPED_BY_PREFERENCE', 'PROVIDER_SENT', 'PROVIDER_FAILED')
   OR provider_status NOT IN ('NOT_CONFIGURED', 'READY_FOR_PROVIDER', 'SENT', 'FAILED');
